### ISSUE TITLE
When copying files via rsync, lsyncd won't watch subfolders

### ISSUE THREAD

**Issue by forgodssake** [axkibe/lsyncd#486] opened 2018-01-18 16:17 UTC
**What happens**
Creating files manually or copying them via scp works as expected, lsync replicates them to all other servers.
 If you copy files via rsync (ex: `rsync -rv $REMOTE_SERVER:/home/joe/videos/ /var/www/sync` ) it will only synchronize the main folder and all the other servers will have the subfolders created but empy.
server 1:
```
/var/www/sync/a.txt
/var/www/sync/b.jpb
/var/www/sync/C/d.txt
/var/www/sync/E/f.jpg
```
other servers:
```
/var/www/sync/a.txt
/var/www/sync/b.jpb
/var/www/sync/C/
/var/www/sync/E/
```
If you check the status file after synchronizing, lsyncd only reports to be watching '/var/www/sync'. Restarting lsyncd synchronizes everything and it reports to be watching all folders.

Every time the rsync command is launched, the following lines appear on the lsyncd.log file:
```
Error: cannot open dir [/var/www/sync//C/].
Error: cannot open dir [/var/www/sync//E/].
```

**Servers setup**

Server OS: RHEL 7.4
Lsyncd version: 2.1.5
Rsync version: 3.0.9

Multiple web servers for static content, users create files in server 1 and they get automatically replicated to all other servers.

Deleting is disabled to prevent human error from deleting everything. .swp files excluded to avoid replicating them when users create a file with vim.

Lsyncd config in server 1:
```
settings {
  delay = 5,
  logfile = "/var/log/lsyncd/lsyncd.log",
  pidfile = "/var/run/lsyncd/lsyncd.pid",
  statusFile = "/var/log/lsyncd/lsyncd-status.log",
  statusInterval = 60 
}

sync {
  default.rsync,
  source = "/var/www/sync",
  target = "foo_lsync@192.168.X.X::var_www_sync",
  rsync = {
    times = false,
    compress = false,
    password_file = "/home/foo_lsync/.rsyncpass",
    checksum = true,
  },
  delete = false,
  exclude = { ".*.swp" }
}
```

**Comment by axkibe** [comment] 2018-01-18 16:40
Lsyncd has no access to C and E, I suggest fixing that on permission level.

**Comment by forgodssake** [comment] 2018-01-19 13:32
It's true that it seems a permission issue, I can see the following log line everytime a folder is added via rsync
`Inotify: addwatch( /C/ )-> -1; err= 13 : Permission denied`

but I don't think it's the issue because:
- Files created manually and via scp have the same permissions and work.
- After running rsync I can restart lsyncd and with the same permissions every folder gets monitored
- inotify_add_watch documentation states that the issuer of the call should have permissions to read the file (it has now, others can read). I'm using ACLs and I've added specific rwx permission to foo_lsync, still not working.

Is there anything else I can test?

Thanks

**Comment by axkibe** [comment] 2018-01-22 09:30
```Inotify: addwatch( /C/ )```
is not normal, it should say, 
```Inotify: addwatch( /var/www/sync/C/ )```

Are you running Lsyncd in a chroot() environment? or any other reason why when it tries to get the realpath() of ```/var/www/sync/``` it returns ```/```?

PS: You might also try updating to Lsyncd 2.2.2

**Comment by axkibe** [comment] 2018-01-22 09:56
Maybe try if 'inotifywatch' from the 'inotify-tools' package has access to watch these directories in the same environment Lsyncd runs under.

I'm 95% certain, your issue resides outside of Lsyncd.

**Comment by axkibe** [comment] 2018-03-09 12:13
I'm closing this for now, as said, it is very likely, whatever the issue is, its outside of Lsyncd.

**Closed by axkibe** 2018-03-09 12:13 UTC
