### ISSUE TITLE
lsyncd doesn't allow use of "/dev/stdin" or "-" for config filename

### ISSUE THREAD

**Issue by gene1wood** [axkibe/lsyncd#361] opened 2015-12-28 22:00 UTC
It would be nice if one could interact with lsyncd like other *nix utilities by passing either `/dev/stdin` or `-` as the config filename and piping in config settings.

The POSIX standard defines a convention that exists in many utilities in the [POSIX.1-2008 : Utility Conventions : Utility Syntax Guidelines : Guideline 13](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html#tag_12_02). This convention is the use of a `-` in place of a filename as a command line argument to indicate `standard input`. Here's an example

```
echo "this is a test" | wc --bytes -
```

which returns the number of bytes in the string "this is a test\n"

This can also be done without the convention of `-` meaning `standard input` like this

```
echo "this is a test" | wc --bytes /dev/stdin
```

Both work.

lsyncd doesn't currently support the `-` convention, and it looks like one of [these two checks](https://github.com/axkibe/lsyncd/blob/cce7db5ebd352690917792848c2aea92c08efdd5/lsyncd.c#L2667-L2693) fails if `/dev/stdin` is passed as the config filename. If one runs

```
echo "sync{bash, source=\"/home/lonewolf/teste1\", target=\"/home/lonewolf/teste2\"}" | lsyncd -nodaemon /dev/stdin
```

The error `Error: Cannot find config file at '/dev/stdin'.` is returned.

Would it be possible to see what about those two tests that causes lsyncd to error out when one passes `/dev/stdin` as the config file? Would it also be possible to accept `-` as the config filename to conform to the POSIX guideline?

**Comment by axkibe** [comment] 2016-05-03 09:07
The issue with this is, in case Lsyncd receives a HUP signal, it makes a soft reset, rereading its input. Which is unclear, should it reread its configuration from stdin on HUP or shouldn't it?

**Comment by gene1wood** [comment] 2016-05-03 13:58
Ah I see. Is it possible to make the reload of config on HUP conditional on the config coming from an actual file? Such that in the case where the user passed "-", reload of config on HUP would not occur.

**Comment by axkibe** [comment] 2016-05-03 14:01
It would require a seperate reload logic just for stdin (or any character device) issue.

**Comment by gene1wood** [comment] 2016-05-03 23:49
Would it make sense to just disable the reload behavior in the case where the user is passing the config through stdin? For example, if the filename is `-` then read the config from stdin and disable the reload behavior.

**Comment by axkibe** [comment] 2016-05-04 09:14
It would have to autodetect similar for all character devices as configs.

Maybe lets go a step back, what is your use case?

**Comment by gene1wood** [comment] 2016-05-04 16:24
Sure, good idea. I'll describe the need and why I thought this might be a good solution.

lsyncd has a large number of settings that the user might want to set when using the tool. All of those settings can be set in a configuration file and passed to lsyncd by putting the filename of the configfile on the command line as an argument. (Examples : `source`, `target` and `exclude`)

A subset of those settings can instead be set on the command line instead of in a configuration file. (Examples : `source` and `target) Much of the time users can get away with only using the settings available on the command line and don't need to create a configuration file to use lsyncd. 

Sometimes though one wants to set a setting not available on the command line (and only available in the config file) and one doesn't want to create a configuration file to do so. A good example of when this is useful is when one's writing documentation and it's much easier to describe to the reader how to run a single command to launch lsyncd vs a series of commands to create a config file (think heredoc bash commands echoing lines into a file) and then call lsyncd passing that temporary config filename as an argument. Another instance where it would be useful to be able to set those settings on the command line is when you're scripting around lsyncd. It's much easier in a script to launch lsyncd with a single command than to create a tempfile with the config, launch lsyncd passing that tempfile as the config filename and then trap on exit to remove the conifg file when done.

My first thought to solve this challenge was to just pass the config file contents in on stdin since that would allow me to pass the settings on the command line and would still function like lsyncd expects as the configuration would come in as a file descriptor, however this doesn't work.

So maybe the tl;dr is that if lsyncd would accept configuration file input over stdin (like many posix tools that take a filename as a command line argument) then the notion of launching lsyncd with a single command line command could be achieved. As you've described, to be able to do this lsyncd would have to notice that the user passed a `-` as the filename, read the config file from stdin, and disable the HUP config reload feature.

**Comment by axkibe** [comment] 2016-05-04 16:43
this didn't describe *your* use case :)

"magically" turning of the HUP feature is something I oppose, reacting on HUPs is a general feature for daemons, commonly expected at least as much as accepting "-" for unix command line utils.

How do other commonly known daemons handle this case?

One thing I could accept is accepting stdin as config file in case of "-nodaemon" is used, which BTW works already! saying '/dev/stdin' at least.

In case Lsyncd is going to daemonize itself, it wants to get realpath() of the config file, so it finds it again, when running as daemon. And this fails for /dev/stdin. BTW: behaving like a daemon should it closes stdin, stdout, stderr when daemonizing itself.

**Comment by gene1wood** [comment] 2016-05-04 17:07
> this didn't describe your use case :)

Heh sorry about that. I want to be able to run a single command to launch lsyncd with the `rsyncssh` module and be able to set the `perms` setting.

> "magically" turning off the HUP feature is something I oppose

Right, agreed. I may not have been clear, my thought was that disabling the HUP driven reload of a config file would only happen in the case that there is no config file because the config is being passed through stdin. If that was clear and you're saying that any disabling of HUP driven config reload regardless of whether there is a config file or not then disregard my clarification.

> reacting on HUPs is a general feature for daemons, commonly expected at least as much as accepting "-" for unix command line utils.

Agreed. I definitely think that lsynd should do exactly what it does currently when it receives a HUP and has loaded it's config from a config file (which is to re-read the config). That makes good sense and is the behavior I'd expect from a daemon.

> How do other commonly known daemons handle this case?

Reading the rest of your comment maybe I'm encountering a different problem than we're talking about. I'll skip this question for the moment.

> One thing I could accept is accepting stdin as config file in case of "-nodaemon" is used, which BTW works already! saying '/dev/stdin' at least.

Oh? That's what this github issue originally calls out, that calling lsyncd with `-nodaemon` and passing `/dev/stdin` causes an error (see above).

> If one runs `echo "sync{bash, source=\"/home/lonewolf/teste1\", target=\"/home/lonewolf/teste2\"}" | lsyncd -nodaemon /dev/stdin` The error `Error: Cannot find config file at '/dev/stdin'`. is returned.

Are you saying that the command in this issue's description should work and should accept `/dev/stdin`?

**Comment by axkibe** [comment] 2016-05-04 17:33
Sorry my failure, I did a test case wrong.

Anyway, the issue is, when receiving a HUP the way lsyncd is coded it completely resets internally, also executing the Lua files another time. If the config file cannot be read again, since its actually a stream, it would have to cache the first time it reads them, which is a major code addition I don't really want to add just for the sake of it.

Btw: currently I think the command line synchronization commands where an error to start with. A config file should always be necessary, and form all reports I get from people using it in practice, they use a config file. Its a remanence of the Lsyncd 1.x series, which used to be c code only, and at first had no config file at all.

**Comment by gene1wood** [comment] 2016-05-04 17:41
> Sorry my failure, I did a test case wrong.

I'm not sure I understand. Are you saying that  `/dev/stdin` should be usable as the config file in `-nodaemon` mode?

> it would have to cache the first time it reads them, which is a major code addition I don't really want to add just for the sake of it.

I totally agree. If enabling some kind of state or caching of the config would be required then yes, don't worry about it. I just thought it might be a simple fix. If it would require anything more than a simple conditional skip it.

> Btw: currently I think the command line synchronization commands where an error to start with. A config file should always be necessary, and form all reports I get from people using it in practice, they use a config file. Its a remanence of the Lsyncd 1.x series, which used to be c code only, and at first had no config file at all.

I'm not sure I understand you but that's ok =)

Also, I don't think I mentioned it Axel, but thanks so much for making lsyncd, it's a very useful tool and I use it frequently.

**Comment by axkibe** [comment] 2016-06-10 08:02
Thank you for your kind words, I'm closing this since yes, doing this properly would be more than a simple conditional somewhere, as the input would need to be cached to survive HUPs.

**Closed by axkibe** 2016-06-10 08:02 UTC
