### ISSUE TITLE
can't sync a file named "~~7F]`B@M_EO73_@%KJA8VN.txt" or "~~7F]`B@M_EO73_@%KJA8VN.jpg"

### ISSUE THREAD

**Issue by abirdman** [axkibe/lsyncd#386] opened 2016-06-21 09:57 UTC
I have add 2851 files  ,but it sync only 1962 files. 

/usr/local/lsyncd/var/lsyncd.log:
Tue Jun 21 17:49:51 2016 Normal: Calling rsync with filter-list of new/modified files/dirs
/123/~~7F\]`B@M_EO73_@%KJA8VN.txt
/123/
/
Tue Jun 21 17:49:51 2016 Exec: /usr/bin/rsync [<] [/123/~~7F\]`B@M_EO73_@%KJA8VN.txt
/123/
/] [-gvzolsptD] [-r] [--delete] [--ignore-errors] [--force] [--from0] [--include-from=-] [--exclude=*] [/data/pic/] [root@172.17.210.233:/data/pic/]
Tue Jun 21 17:49:51 2016 Exec: one-sweeped pipe
sending incremental file list
123/

sent 117 bytes  received 16 bytes  10.64 bytes/sec
total size is 0  speedup is 0.00
Tue Jun 21 17:50:03 2016 Normal: Finished a list after exitcode: 0

**Comment by axkibe** [comment] 2016-06-21 10:15
Do your filename include 0 characters?

**Comment by abirdman** [comment] 2016-06-21 10:26
"~~7F]`B@M_EO73_@%KJA8VN.txt"  include 0 characters,"~~7F]`B@M_EO73_@%KJA8VN.jpg" is a real image file include 28kb content . If I rename "~~7F]`B@M_EO73_@%KJA8VN.jpg"  to "111.jpg",it can sync normal.

**Comment by axkibe** [comment] 2016-06-21 10:28
It doesn't matter what the content is. When the filename contains a 0 character it doesn't work.

Lsyncd has to somehow delimit filename when communicating with rsync. You can change it to use '\n' as delimeters instead, but then filename wont work that contain that instead.

**Comment by abirdman** [comment] 2016-06-21 10:37
But file name is "~~7F]`B@M_EO73_@%KJA8VN.jpg",didn't have a 0 character .

**Comment by axkibe** [comment] 2016-06-21 10:50
Can you please try figure out, which character in the filename makes it stop to work?

**Comment by abirdman** [comment] 2016-06-21 10:56
I will try every single character in "~~7F]`B@M_EO73_@%KJA8VN.jpg" , when I find it , i'll tell you,thanks!

**Comment by mdiehn** [comment] 2016-06-21 13:59
By "0 character" do you mean "null?"

On Tue, Jun 21, 2016 at 6:56 AM, abirdman <notifications@github.com> wrote:

> I will try every single character in "~~7F]`B@M_EO73_@%KJA8VN.jpg" , when
> I find it , i'll tell you,thanks!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/axkibe/lsyncd/issues/386#issuecomment-227406611>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AOpoVSpuTwxwrss41cPxBFm0DsJ0fQqKks5qN8NkgaJpZM4I6jjs>
> .
>



-- 
Mike Diehn
Enfield, NH
mike@diehn.net

**Comment by axkibe** [comment] 2016-06-21 14:21
Yes, it was just a guess. I tried it, it doesn't seem to be allowed on Linux anyway.

I remember there are some UTF encoding that have these in strings, but as filenames its disallowed anyway.

It must be some other character rsync confuses in the filter file and needs to be escaped by Lsyncd.

**Comment by axkibe** [comment] 2016-06-21 14:22
And with "filter file" I mean the on the fly generated filter rules that Lsyncd pipes through stdin to rsync. Its never a real file.

**Comment by mdiehn** [comment] 2016-06-21 14:49
Yeah, nulls and / aren't allowed in Unix pathnames. Which let's us use
nulls as delimiters as in

find sourcedir/ -type f -print0 | cpio -0 -pmud destinationdir/


But you knew that, right? Duh. Sorry!


On Tue, Jun 21, 2016 at 10:22 AM, Axel Kittenberger <
notifications@github.com> wrote:

> And with "filter file" I mean the on the fly generated filter rules that
> Lsyncd pipes through stdin to rsync. Its never a real file.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/axkibe/lsyncd/issues/386#issuecomment-227455360>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AOpoVbUTb5PoWSwI2Do6aUTD1YsS7Iyuks5qN_OugaJpZM4I6jjs>
> .
>



-- 
Mike Diehn
Enfield, NH
mike@diehn.net

**Comment by axkibe** [comment] 2016-06-21 14:53
Yes, and I changed Lsyncd to use 0 delimiters a while back, since it was critized for using newlines before.

It was just a guess seeing a strange string that looked liked missrepresented UTF encoding, but as said, I wasn't aware the Linux kernel forbidds it anyway. It must be some other character rsync understands as special and needs an escaping before it. For *?[] Lsyncd does this:

```
        return p:
            gsub( '%?', '\\?' ):
            gsub( '%*', '\\*' ):
            gsub( '%[', '\\[' ):
            gsub( '%]', '\\]' )
```

**Comment by abirdman** [comment] 2016-06-22 07:55
I find the character is ]

**Comment by axkibe** [comment] 2016-06-27 07:28
Fixed in GIT head.

The cause of the issue is appearent in this line of the rsync documentation:

> rsync chooses between doing a simple string match and wildcard matching by checking if the pattern contains one of these three wildcard characters: '*', '?', and '[' .

So if only a ] is there and not * ? or [ rsync consideres the filter rule to be "simple" and will interpred Lsyncd's escaping of ] as \] literally and thus won't match your file

**Closed by axkibe** 2016-06-27 07:28 UTC
