### ISSUE TITLE
Lsync synchronization one time will not synchronize

### ISSUE THREAD

**Issue by PatrickGG** [axkibe/lsyncd#508] opened 2018-05-14 04:44 UTC
Lsync synchronization one time will not synchronize.Process existence.
To configure:
settings {
        logfile = "/work/logs/lsyncd/lsyncd.log",
        statusFile = "/work/servers/lsyncd/lsyncd.status",
        pidfile = "/work/servers/lsyncd/lsyncd.pid",
        statusInterval = 20
}

sync {
        default.rsync,
                source = "/work/logs/nginx",
                target = "x.x.x.x:/work/back",
                delay = 15,
        rsync = {
                binary = "/usr/bin/rsync",
                archive = true,
                compress = true,
                verbose = true,
                rsh = "/usr/bin/ssh -p 9201"
        }
}

info log:
sent 12029814 bytes  received 349414 bytes  707384.46 bytes/sec
total size is 1022652824  speedup is 82.61
Mon May 14 11:58:54 2018 Call: collectProcess( )
Mon May 14 11:58:54 2018 Delay: collected an event
Mon May 14 11:58:54 2018 Normal: Startup of "/work/logs/nginx/" finished: 0
Mon May 14 11:58:54 2018 Delay: Finish of Init on /work/logs/nginx/ = 0
Mon May 14 11:58:54 2018 Call: cycle( )
Mon May 14 11:58:54 2018 Function: invokeActions( "Sync1", (Timestamp: 26662134.27) )
Mon May 14 11:58:54 2018 Function: write( (Timestamp: 26662134.27) )
Mon May 14 11:58:54 2018 Statusfile: setting alarm: (Timestamp: 26662154.27)
Mon May 14 11:58:54 2018 Call: getAlarm( )
Mon May 14 11:58:54 2018 Alarm: runner.getAlarm returns: (Timestamp: 26662154.27)
Mon May 14 11:58:54 2018 Masterloop: going into select ( timeout 20 seconds )
Mon May 14 11:59:14 2018 Call: cycle( )
Mon May 14 11:59:14 2018 Function: invokeActions( "Sync1", (Timestamp: 26662154.29) )
Mon May 14 11:59:14 2018 Function: write( (Timestamp: 26662154.29) )
Mon May 14 11:59:14 2018 Statusfile: writing now
Mon May 14 11:59:14 2018 Call: getAlarm( )
Mon May 14 11:59:14 2018 Alarm: runner.getAlarm returns: (false)
Mon May 14 11:59:14 2018 Masterloop: going into select ( no timeout )
Mon May 14 12:36:42 2018 Debug: daemonizing now.
Mon May 14 12:36:42 2018 Function: Inotify.addWatch( /work/logs/nginx/ )
Mon May 14 12:36:42 2018 Inotify: addwatch( /work/logs/nginx/ )-> 1 
Mon May 14 12:36:42 2018 Call: getAlarm( )
Mon May 14 12:36:42 2018 Alarm: runner.getAlarm returns: (true)
Mon May 14 12:36:42 2018 Masterloop: immediately handling delays.
Mon May 14 12:36:42 2018 Call: cycle( )
Mon May 14 12:36:42 2018 Function: invokeActions( "Sync1", (Timestamp: 26664402.19) )
Mon May 14 12:36:42 2018 Normal: recursive startup rsync: /work/logs/nginx/ -> 183.60.191.99:/work/back/
Mon May 14 12:36:42 2018 Exec: /usr/bin/rsync [--delete] [--ignore-errors] [-gpvzsoltD] [--rsh=/usr/bin/ssh -p 9201] [-r] [/work/logs/nginx/] [x.x.x.x:/work/back/]
Mon May 14 12:36:42 2018 Function: write( (Timestamp: 26664402.19) )
Mon May 14 12:36:42 2018 Statusfile: writing now
Mon May 14 12:36:42 2018 Call: getAlarm( )
Mon May 14 12:36:42 2018 Alarm: runner.getAlarm returns: (false)
Mon May 14 12:36:42 2018 Masterloop: going into select ( no timeout )
sending incremental file list
xxx.api.access.log
xxx.access.log
xxx.access.log
xxxxx.access.log

sent 4008433 bytes  received 351476 bytes  185528.04 bytes/sec
total size is 1088373051  speedup is 249.63
Mon May 14 12:37:05 2018 Call: collectProcess( )
Mon May 14 12:37:05 2018 Delay: collected an event
Mon May 14 12:37:05 2018 Normal: Startup of "/work/logs/nginx/" finished.
Mon May 14 12:37:05 2018 Delay: Finish of Init on /work/logs/nginx/ = 0
Mon May 14 12:37:05 2018 Call: cycle( )
Mon May 14 12:37:05 2018 Function: invokeActions( "Sync1", (Timestamp: 26664425.03) )
Mon May 14 12:37:05 2018 Function: write( (Timestamp: 26664425.03) )
Mon May 14 12:37:05 2018 Statusfile: setting alarm: (Timestamp: 26664445.03)
Mon May 14 12:37:05 2018 Call: getAlarm( )
Mon May 14 12:37:05 2018 Alarm: runner.getAlarm returns: (Timestamp: 26664445.03)
Mon May 14 12:37:05 2018 Masterloop: going into select ( timeout 20 seconds )

Mon May 14 12:37:25 2018 Call: cycle( )
Mon May 14 12:37:25 2018 Function: invokeActions( "Sync1", (Timestamp: 26664445.05) )
Mon May 14 12:37:25 2018 Function: write( (Timestamp: 26664445.05) )
Mon May 14 12:37:25 2018 Statusfile: writing now
Mon May 14 12:37:25 2018 Call: getAlarm( )
Mon May 14 12:37:25 2018 Alarm: runner.getAlarm returns: (false)
Mon May 14 12:37:25 2018 Masterloop: going into select ( no timeout )

Not synchronizing.

**Comment by axkibe** [comment] 2018-05-14 06:55
Most likely:
http://axkibe.github.io/lsyncd/faq/nothing-after-startup/

**Comment by PatrickGG** [comment] 2018-05-14 09:14
@axkibe I don't quite understand the meaning. I've read the document.

**Comment by saulzy** [comment] 2018-05-21 17:43
The source  machine configure ssh-copy-id to dst machine . see  rsync log .

**Comment by axkibe** [comment] 2018-05-22 07:17
It means '/work' is either a network drive.
Or possibly, nginx is not closing the log files. Eitherway Lsyncd does not get notifcations from the kernel, so it cannot know if things changed. The issue is most likely not a Lsyncd issue.

Run with ```-log Inotify```  if inotify notifcations do arive and Lsyncd does not react on it, reopen the issue. Otherwise fix whatever causes them not to be sent.

**Closed by axkibe** 2018-05-22 07:17 UTC
