### ISSUE TITLE
Error: unknown event(831) / event(2125) in fsevents.

### ISSUE THREAD

**Issue by rockhouse** [axkibe/lsyncd#244] opened 2013-10-25 15:10 UTC
My lsyncd keeps on crashing after initial sync with this error message:
Error: unknown event(831) in fsevents

Strange is that the initial scan works just fine and the moment when it is crashing varies also, so I do not know what is triggering it. Any ideas? 

EDIT: It crashed now with the error code: 
Error: unknown event(2125) in fsevents.

**Comment by qris** [comment] 2016-06-03 12:16
This just happened to me on Yosemite.

**Comment by axkibe** [comment] 2016-06-03 12:43
Yes, the whole FsEvents part of Lsyncd should be rewritten. However, unless we find someone willing to do that I'm thinking of dropping fsevents from Lsyncd all together, the current implementation is buggy and uses non-documented interfaces.

**Comment by axkibe** [comment] 2016-12-05 14:25
Duplicate of #204

**Closed by axkibe** 2016-12-05 14:25 UTC

**Comment by PetrochukM** [comment] 2023-10-20 18:16
Hey There! This issue is coming up again, and I am not sure how to debug it. I have been trying to use `fs_usage` to monitor the event but to no avail. This is preventing me from using `lsyncd`, it crashes right after the first sync on my Macbook, every time.
