### ISSUE TITLE
Does not link

### ISSUE THREAD

**Issue by BSVogler** [axkibe/lsyncd#408] opened 2016-11-30 16:30 UTC
This tools looks like the perfect tool. 👍 
It would be nice to have a binary for download, so I had to build it by myself. I needed Lua for that, so I installed the latest version of Lua (5.3) from the official website.

Now I get this when I `make`:
> [ 12%] Generating defaults.out
> Compiling built-in default configs
> [ 25%] Generating runner.out
> Compiling built-in runner
> [ 37%] Generating runner.c
> Generating built-in runner linkable
> [ 50%] Generating defaults.c
> Generating built-in default configs
> Scanning dependencies of target lsyncd
> [ 62%] Building C object CMakeFiles/lsyncd.dir/lsyncd.c.o
> [ 75%] Building C object CMakeFiles/lsyncd.dir/runner.c.o
> [ 87%] Building C object CMakeFiles/lsyncd.dir/defaults.c.o
> [100%] Building C object CMakeFiles/lsyncd.dir/inotify.c.o
> Linking C executable lsyncd
> /usr/local/lib/liblua.a(loadlib.o): In Funktion `lookforfunc':
> loadlib.c:(.text+0x502): Nicht definierter Verweis auf `dlsym'
> loadlib.c:(.text+0x549): Nicht definierter Verweis auf `dlerror'
> loadlib.c:(.text+0x576): Nicht definierter Verweis auf `dlopen'
> loadlib.c:(.text+0x5ed): Nicht definierter Verweis auf `dlerror'
> /usr/local/lib/liblua.a(loadlib.o): In Funktion `gctm':
> loadlib.c:(.text+0x781): Nicht definierter Verweis auf `dlclose'
> collect2: error: ld returned 1 exit status
> make[2]: *** [lsyncd] Fehler 1
> make[1]: *** [CMakeFiles/lsyncd.dir/all] Fehler 2
> make: *** [all] Fehler 2

Any help, how I fix this?

Cheers,
Benedikt

**Comment by axkibe** [comment] 2016-11-30 16:43
Did you try the latest GIT version? Looks like a Lua 5.3 vs. 5.1 version issue that should be fixed in latest sources.

Or alternative use Lua 5.1

**Comment by BSVogler** [comment] 2016-11-30 17:14
@axkibe yes, I used the latest git version.
How do downgrade? I installed lua 5.1 but I get the same error. I guess it still uses 5.3

**Comment by axkibe** [comment] 2016-11-30 17:50
probier mal:
```
cmake -DCMAKE_C_FLAGS=-ldl .
make clean
make
```

**Comment by BSVogler** [comment] 2016-11-30 18:01
sorry, this did not solve the error

**Comment by axkibe** [comment] 2016-11-30 18:07
Please copy/paste the whole output of
```
cmake -DCMAKE_C_FLAGS=-ldl .
make clean
make VERBOSE=1
```

**Comment by BSVogler** [comment] 2016-11-30 18:12
> /usr/bin/cmake -H/home/wulo8720/lsyncd-master -B/home/wulo8720/lsyncd-master/build --check-build-system CMakeFiles/Makefile.cmake 0
> /usr/bin/cmake -E cmake_progress_start /home/wulo8720/lsyncd-master/build/CMakeFiles /home/wulo8720/lsyncd-master/build/CMakeFiles/progress.marks
> make -f CMakeFiles/Makefile2 all
> make[1]: Verzeichnis »/home/wulo8720/lsyncd-master/build« wird betreten
> make -f CMakeFiles/lsyncd.dir/build.make CMakeFiles/lsyncd.dir/depend
> make[2]: Verzeichnis »/home/wulo8720/lsyncd-master/build« wird betreten
> /usr/bin/cmake -E cmake_progress_report /home/wulo8720/lsyncd-master/build/CMakeFiles 4
> [ 12%] Generating defaults.out
> /usr/bin/cmake -E echo Compiling\ built-in\ default\ configs
> Compiling built-in default configs
> /usr/local/bin/luac -o defaults.out /home/wulo8720/lsyncd-master/default.lua /home/wulo8720/lsyncd-master/default-rsync.lua /home/wulo8720/lsyncd-master/default-rsyncssh.lua /home/wulo8720/lsyncd-master/default-direct.lua
> /usr/bin/cmake -E cmake_progress_report /home/wulo8720/lsyncd-master/build/CMakeFiles 3
> [ 25%] Generating runner.out
> /usr/bin/cmake -E echo Compiling\ built-in\ runner
> Compiling built-in runner
> /usr/local/bin/luac -o runner.out /home/wulo8720/lsyncd-master/lsyncd.lua
> /usr/bin/cmake -E cmake_progress_report /home/wulo8720/lsyncd-master/build/CMakeFiles 1
> [ 37%] Generating runner.c
> /usr/bin/cmake -E echo Generating\ built-in\ runner\ linkable
> Generating built-in runner linkable
> /usr/local/bin/lua /home/wulo8720/lsyncd-master/bin2carray.lua runner.out runner runner.c
> /usr/bin/cmake -E cmake_progress_report /home/wulo8720/lsyncd-master/build/CMakeFiles 2
> [ 50%] Generating defaults.c
> /usr/bin/cmake -E echo Generating\ built-in\ default\ configs
> Generating built-in default configs
> /usr/local/bin/lua /home/wulo8720/lsyncd-master/bin2carray.lua defaults.out defaults defaults.c
> cd /home/wulo8720/lsyncd-master/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/wulo8720/lsyncd-master /home/wulo8720/lsyncd-master /home/wulo8720/lsyncd-master/build /home/wulo8720/lsyncd-master/build /home/wulo8720/lsyncd-master/build/CMakeFiles/lsyncd.dir/DependInfo.cmake --color=
> Dependee "/home/wulo8720/lsyncd-master/build/defaults.c" is newer than depends file "/home/wulo8720/lsyncd-master/build/CMakeFiles/lsyncd.dir/depend.internal".
> Dependee "/home/wulo8720/lsyncd-master/build/runner.c" is newer than depends file "/home/wulo8720/lsyncd-master/build/CMakeFiles/lsyncd.dir/depend.internal".
> Clearing dependencies in "/home/wulo8720/lsyncd-master/build/CMakeFiles/lsyncd.dir/depend.make".
> Scanning dependencies of target lsyncd
> make[2]: Verzeichnis »/home/wulo8720/lsyncd-master/build« wird verlassen
> make -f CMakeFiles/lsyncd.dir/build.make CMakeFiles/lsyncd.dir/build
> make[2]: Verzeichnis »/home/wulo8720/lsyncd-master/build« wird betreten
> /usr/bin/cmake -E cmake_progress_report /home/wulo8720/lsyncd-master/build/CMakeFiles 5
> [ 62%] Building C object CMakeFiles/lsyncd.dir/lsyncd.c.o
> /usr/bin/cc   -ldl -I/usr/local/include -I/home/wulo8720/lsyncd-master/build    -o CMakeFiles/lsyncd.dir/lsyncd.c.o   -c /home/wulo8720/lsyncd-master/lsyncd.c
> /usr/bin/cmake -E cmake_progress_report /home/wulo8720/lsyncd-master/build/CMakeFiles 6
> [ 75%] Building C object CMakeFiles/lsyncd.dir/runner.c.o
> /usr/bin/cc   -ldl -I/usr/local/include -I/home/wulo8720/lsyncd-master/build    -o CMakeFiles/lsyncd.dir/runner.c.o   -c /home/wulo8720/lsyncd-master/build/runner.c
> /usr/bin/cmake -E cmake_progress_report /home/wulo8720/lsyncd-master/build/CMakeFiles 7
> [ 87%] Building C object CMakeFiles/lsyncd.dir/defaults.c.o
> /usr/bin/cc   -ldl -I/usr/local/include -I/home/wulo8720/lsyncd-master/build    -o CMakeFiles/lsyncd.dir/defaults.c.o   -c /home/wulo8720/lsyncd-master/build/defaults.c
> /usr/bin/cmake -E cmake_progress_report /home/wulo8720/lsyncd-master/build/CMakeFiles 8
> [100%] Building C object CMakeFiles/lsyncd.dir/inotify.c.o
> /usr/bin/cc   -ldl -I/usr/local/include -I/home/wulo8720/lsyncd-master/build    -o CMakeFiles/lsyncd.dir/inotify.c.o   -c /home/wulo8720/lsyncd-master/inotify.c
> Linking C executable lsyncd
> /usr/bin/cmake -E cmake_link_script CMakeFiles/lsyncd.dir/link.txt --verbose=1
> /usr/bin/cc  -ldl    CMakeFiles/lsyncd.dir/lsyncd.c.o CMakeFiles/lsyncd.dir/runner.c.o CMakeFiles/lsyncd.dir/defaults.c.o CMakeFiles/lsyncd.dir/inotify.c.o  -o lsyncd -rdynamic /usr/local/lib/liblua.a -lm 
> /usr/local/lib/liblua.a(loadlib.o): In Funktion `ll_loadfunc':
> loadlib.c:(.text+0x84a): Nicht definierter Verweis auf `dlsym'
> loadlib.c:(.text+0x889): Nicht definierter Verweis auf `dlerror'
> loadlib.c:(.text+0x8a9): Nicht definierter Verweis auf `dlopen'
> loadlib.c:(.text+0x8bc): Nicht definierter Verweis auf `dlerror'
> /usr/local/lib/liblua.a(loadlib.o): In Funktion `gctm':
> loadlib.c:(.text+0xb7c): Nicht definierter Verweis auf `dlclose'
> collect2: error: ld returned 1 exit status
> make[2]: *** [lsyncd] Fehler 1
> make[2]: Verzeichnis »/home/wulo8720/lsyncd-master/build« wird verlassen
> make[1]: *** [CMakeFiles/lsyncd.dir/all] Fehler 2
> make[1]: Verzeichnis »/home/wulo8720/lsyncd-master/build« wird verlassen
> make: *** [all] Fehler 2

**Comment by axkibe** [comment] 2016-11-30 18:22
The issue is here,

```> /usr/bin/cc  -ldl    CMakeFiles/lsyncd.dir/lsyncd.c.o CMakeFiles/lsyncd.dir/runner.c.o CMakeFiles/lsyncd.dir/defaults.c.o CMakeFiles/lsyncd.dir/inotify.c.o  -o lsyncd -rdynamic /usr/local/lib/liblua.a -lm``

WIth ```/usr/local/lib/liblua.a``` it tries to link Lua statically, but since it has dynamic module loading enabling, it fails. I don't know why cmake decides in your case to link lua statically it should put "-llua5.3" there instead.

I'd make sure that the liblua5.3.so is installed and findable somewhere at common library paths, then erase everything of cmake and start afresh.

**Comment by axkibe** [comment] 2016-11-30 18:26
Or just run that line manually with the .a thing replaced  by -llua5.3 or -llua (whatever your lua library is called)

**Comment by axkibe** [comment] 2016-12-05 14:01
I close this for now, my conclusion is, you got a wiered installation of Lua (I don't know what and why), thats why cmake bugs out. Reopen or open a new issue if this problem persists.

**Closed by axkibe** 2016-12-05 14:01 UTC

**Comment by zhangbei59** [comment] 2024-06-19 03:29
> make VERBOSE=1

/usr/local/lib/liblua.a -lm -ldl  这样也可以2.3.1版本
